name: Update HopToDesk Flatpak

on:
  schedule:
    - cron: "0 3 * * *"   # Runs daily at 03:00 UTC (adjust as needed)
  workflow_dispatch:      # Manual trigger
  pull_request:

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  
jobs:
  update-flatpak:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Flathub repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone flathub
        run: |
            git clone https://github.com/flathub/com.hoptodesk.HopToDesk.git --depth 1
            cd com.hoptodesk.HopToDesk
            # Fetch just the single commit you need
            cd ..
            cp -r com.hoptodesk.HopToDesk/com.hoptodesk.HopToDesk.json ./flatpak/com.hoptodesk.HopToDesk.json
            rm -rf com.hoptodesk.HopToDesk

      # Install dependencies: flatpak and flatpak-builder, plus jq and wget for processing.
      - name: Install dependencies
        run: |
          # Wait for dpkg lock to be released (if held by another process)
          while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
            echo "Waiting for dpkg lock to be released..."
            sleep 1
          done
          sudo bash -c 'apt-get update && apt-get -y install flatpak flatpak-builder jq wget'

      # Add Flathub remote in user mode.
      - name: Add Flathub remote
        run: |
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      
      # Download the latest HopToDesk deb package from its working URL.
      - name: Download latest HopToDesk deb package
        run: |
          wget -O hoptodesk.deb "https://www.hoptodesk.com/hoptodesk.deb"

      # Compute the SHA256 checksum of the downloaded deb file.
      - name: Compute SHA256 of HopToDesk deb
        id: compute_sha
        run: |
          SHA256=$(sha256sum hoptodesk.deb | cut -d' ' -f1)
          echo "Computed SHA256: $SHA256"
          echo "HOPTO_SHA256=$SHA256" >> $GITHUB_ENV

      # Extract the package version from the deb metadata.
      - name: Extract version from deb package
        id: extract_version
        run: |
          ver=$(dpkg-deb --field hoptodesk.deb Version | tr -d '\n')
          echo "Extracted version: $ver"
          echo "HOPTO_VERSION=$ver" >> $GITHUB_ENV
      
      - name: Set new URL for HopToDesk deb package
        run: |
          # Change the URL below if you wish to use a different source.
          echo "HOPTO_NEW_URL=https://www.hoptodesk.com/hoptodesk.deb" >> $GITHUB_ENV

      - name: Update Flatpak manifest (com.hoptodesk.HopToDesk.json)
        run: |
          jq --arg ver "$HOPTO_VERSION" \
            --arg sha "$HOPTO_SHA256" \
            --arg url "$HOPTO_NEW_URL" \
            '(.version) = $ver |
              (.modules[] |=
                if type=="object" then
                  # Update the sources array: the deb package URL/sha and the desktop file path.
                  (if .sources then
                      .sources |= map(
                        if (.url? and .url == "https://www.hoptodesk.com/hoptodesk-1.42.1-0-x86_64.deb")
                        then (.url = $url | .sha256 = $sha)
                        else .
                        end
                      )
                  else . end)
                else
                  .
                end)' ./flatpak/com.hoptodesk.HopToDesk.json > tmp_manifest.json && mv tmp_manifest.json ./flatpak/com.hoptodesk.HopToDesk.json
      
      # 12. Push the changes and create a Pull Request in the upstream repository.
      - name: Send pull-request
        run: |
          LATEST_TAG=$(git describe --tags --always --abbrev=0)
          UPSTREAM_REPO="https://github.com/flathub/com.hoptodesk.HopToDesk"
          FORK_REPO="https://github.com/danyal97/com.hoptodesk.HopToDesk"
          FOLDER="com.hoptodesk.HopToDesk"
          BRANCH_NAME="updated-hoptodesk-version"

          # Clone the upstream repository and change working directory to the folder it was cloned to.
          git clone --depth=1 --branch=master $UPSTREAM_REPO
          cd $FOLDER

          # Setup the committers identity.
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          # Create a new feature branch for the changes.
          git checkout -b $BRANCH_NAME

          # Update the script files to the latest version.
          cp -r ../flatpak/com.hoptodesk.HopToDesk.json com.hoptodesk.HopToDesk.json

          # Commit the changes.
          git add .
          git commit -m "updated-hoptodesk-version"

          # Add your fork as a remote.
          git remote add fork $FORK_REPO

          # Push the feature branch to your fork repository.
          git push https://${GH_TOKEN}@github.com/danyal97/com.hoptodesk.HopToDesk.git $BRANCH_NAME

          gh pr create \
            --body "" \
            --title "updated-hoptodesk-version" \
            --head "danyal97:$BRANCH_NAME" \
            --base "master"